import type { Metadata } from "next"
import Link from "next/link"
import {
  ArrowRight,
  BarChart3,
  Brain,
  CalendarDays,
  Globe,
  Shield,
  Target,
  TrendingUp,
  Trophy,
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { FAQSection } from "@/components/FAQSection"
import { EmptyState } from "@/components/EmptyState"
import { JsonLd, faqJsonLd } from "@/lib/jsonld"
import { getHomeUpcoming } from "@/lib/football/queries"
import { FixtureList } from "@/components/football/FixtureList"

export const metadata: Metadata = {
  title: "AI Football Predictions & Match Forecasts | AI Predictor",
  description:
    "AI football predictions for the 2026 World Cup, alongside live Champions League and Premier League fixtures and results.",
  openGraph: {
    title: "AI Football Predictions & Match Forecasts | AI Predictor",
    description:
      "AI football predictions for the 2026 World Cup, alongside live Champions League and Premier League fixtures and results.",
  },
}

export const dynamic = "force-dynamic"

const homeFAQs = [
  {
    question: "What football competitions does AI Predictor cover?",
    answer:
      "AI Predictor features the 2026 World Cup archive — including match predictions, team profiles, group predictions and winner odds — alongside live Champions League and Premier League fixtures and recent results. AI-powered predictions for the Champions League and Premier League are in development and will be published once the match model is validated.",
  },
  {
    question: "How are the football predictions generated?",
    answer:
      "Predictions are generated by a data-driven model that weighs team strength, FIFA rankings, recent form, head-to-head history and squad information to estimate win, draw and loss probabilities for each match.",
  },
  {
    question: "Are football predictions guaranteed to be correct?",
    answer:
      "No. Football is unpredictable and no forecast can be guaranteed. Our predictions are for informational and entertainment purposes only.",
  },
  {
    question: "When are match predictions updated?",
    answer:
      "Predictions are updated as verified match data becomes available. During active competitions, match forecasts are refreshed as new fixtures and confirmed results are published.",
  },
  {
    question: "Can I use the Match Simulator for any teams?",
    answer:
      "Yes. The Match Simulator lets you pick any two teams and get an instant prediction with a win probability and a predicted score.",
  },
]

const competitions = [
  {
    title: "Champions League",
    icon: Trophy,
    description:
      "Live Champions League fixtures, recent results and match data for Europe's premier club competition.",
    href: "/champions-league",
    badge: "Fixtures Available",
    cta: "View fixtures",
  },
  {
    title: "Premier League",
    icon: Shield,
    description:
      "Live Premier League fixtures, recent results and match data for the English top flight.",
    href: "/premier-league",
    badge: "Fixtures Available",
    cta: "View fixtures",
  },
  {
    title: "World Cup 2026",
    icon: Globe,
    description:
      "Browse our archived World Cup predictions, match forecasts and model results from the 2026 tournament.",
    href: "/world-cup/2026",
    badge: "Archive",
    cta: "View predictions",
  },
]

const features = [
  {
    icon: BarChart3,
    title: "Win Probability Analysis",
    description: "Home, draw and away probabilities for every match, updated as data changes.",
  },
  {
    icon: Target,
    title: "Predicted Scorelines",
    description: "Data-driven score forecasts generated before kickoff for each fixture.",
  },
  {
    icon: TrendingUp,
    title: "Prediction Tracking",
    description: "Transparent comparison between our predictions and the actual results.",
  },
]

const archiveLinks = [
  {
    label: "Match Predictions",
    href: "/predictions",
    description: "World Cup 2026 match forecasts and watch calendar",
  },
  {
    label: "Winner Predictions",
    href: "/winner-predictions",
    description: "Championship odds for all 48 teams",
  },
  {
    label: "Team Profiles",
    href: "/teams",
    description: "All 48 nations with rankings and key players",
  },
  {
    label: "Group Predictions",
    href: "/2026-world-cup-group-predictions",
    description: "Group-by-group forecasts",
  },
  {
    label: "Match Simulator",
    href: "/simulator",
    description: "Predict any matchup instantly",
  },
]

const steps = [
  {
    icon: CalendarDays,
    title: "Collect Match Data",
    description: "Gather fixtures, results and team statistics from verified sources.",
  },
  {
    icon: Brain,
    title: "Analyze Team Strength",
    description: "Weight form, rankings, head-to-head history and squad quality.",
  },
  {
    icon: BarChart3,
    title: "Generate Probabilities",
    description: "Estimate the likelihood of a win, draw or loss for each team.",
  },
  {
    icon: TrendingUp,
    title: "Track Actual Results",
    description: "Compare forecasts against real outcomes to measure accuracy.",
  },
]

export default async function HomePage() {
  const groups = await getHomeUpcoming(3)
  const upcomingGroups = groups.filter((group) => group.fixtures.length > 0)

  return (
    <>
      <JsonLd data={faqJsonLd(homeFAQs)} />

      {/* Hero */}
      <section className="border-b bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 text-white">
        <div className="container mx-auto max-w-7xl px-4 py-16 md:py-24">
          <div className="mx-auto max-w-3xl text-center">
            <Badge variant="success" className="mb-4">
              AI-Powered Football Analysis
            </Badge>
            <h1 className="mb-6 text-4xl font-extrabold tracking-tight md:text-5xl lg:text-6xl">
              AI Football Predictions
            </h1>
            <p className="mx-auto mb-8 max-w-2xl text-lg text-slate-300 md:text-xl">
              AI predictions for the 2026 World Cup, alongside live Champions League and Premier League
              fixtures and results.
            </p>
            <div className="flex flex-col justify-center gap-3 sm:flex-row">
              <Link href="/world-cup/2026">
                <Button size="xl" className="w-full bg-sports-green hover:bg-sports-green/90 sm:w-auto">
                  World Cup Predictions <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              </Link>
              <Link href="/simulator">
                <Button
                  size="xl"
                  variant="outline"
                  className="w-full border-white/30 bg-transparent text-white hover:bg-white/10 hover:text-white sm:w-auto"
                >
                  Match Simulator
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Competition Selector */}
      <section className="container mx-auto max-w-7xl px-4 py-16">
        <div className="mb-8 text-center">
          <h2 className="text-3xl font-bold tracking-tight">Explore Competitions</h2>
          <p className="mx-auto mt-2 max-w-2xl text-muted-foreground">
            Choose a competition to explore fixtures, results and predictions.
          </p>
        </div>
        <div className="grid gap-6 md:grid-cols-3">
          {competitions.map((comp) => (
            <Link key={comp.href} href={comp.href} className="group">
              <Card className="h-full transition-shadow hover:shadow-md">
                <CardHeader>
                  <div className="mb-2 flex items-center justify-between">
                    <comp.icon className="h-8 w-8 text-sports-green" />
                    <Badge variant={comp.badge === "Archive" ? "secondary" : "success"}>{comp.badge}</Badge>
                  </div>
                  <CardTitle className="group-hover:text-sports-green">{comp.title}</CardTitle>
                  <CardDescription>{comp.description}</CardDescription>
                </CardHeader>
                <CardContent>
                  <span className="inline-flex items-center gap-1 text-sm font-medium text-sports-green">
                    {comp.cta} <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
                  </span>
                </CardContent>
              </Card>
            </Link>
          ))}
        </div>
      </section>

      {/* Upcoming Football Matches */}
      <section id="predictions" className="scroll-mt-16 border-t bg-muted/30">
        <div className="container mx-auto max-w-7xl px-4 py-16">
          <div className="mb-8 text-center">
            <h2 className="text-3xl font-bold tracking-tight">Upcoming Football Matches</h2>
            <p className="mx-auto mt-2 max-w-2xl text-muted-foreground">
              Upcoming Champions League and Premier League fixtures.
            </p>
          </div>
          {upcomingGroups.length === 0 ? (
            <EmptyState
              icon={CalendarDays}
              title="No upcoming matches"
              description="No upcoming matches are currently available."
              note="Our World Cup 2026 predictions remain available in the archive below."
            />
          ) : (
            <div className="space-y-10">
              {upcomingGroups.map((group) => (
                <div key={group.competition.slug}>
                  <div className="mb-4 flex items-center justify-between gap-3">
                    <h3 className="text-xl font-semibold tracking-tight">
                      {group.competition.shortName ?? group.competition.name}
                    </h3>
                    <Link
                      href={`/${group.competition.slug}/matches`}
                      className="text-sm font-medium text-sports-green hover:underline"
                    >
                      View all matches
                    </Link>
                  </div>
                  <FixtureList
                    fixtures={group.fixtures}
                    emptyMessage="No upcoming matches are currently available."
                  />
                </div>
              ))}
            </div>
          )}
        </div>
      </section>

      {/* What You'll Get */}
      <section className="container mx-auto max-w-7xl px-4 py-16">
        <div className="mb-8 text-center">
          <h2 className="text-3xl font-bold tracking-tight">What You&apos;ll Get</h2>
          <p className="mx-auto mt-2 max-w-2xl text-muted-foreground">
            Clear, data-driven forecasts designed to help you understand every match.
          </p>
        </div>
        <div className="grid gap-6 md:grid-cols-3">
          {features.map((feature) => (
            <Card key={feature.title} className="h-full">
              <CardHeader>
                <feature.icon className="mb-2 h-8 w-8 text-sports-blue" />
                <CardTitle>{feature.title}</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground">{feature.description}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* World Cup 2026 Archive */}
      <section className="border-t bg-muted/30">
        <div className="container mx-auto max-w-7xl px-4 py-16">
          <div className="mb-8 text-center">
            <h2 className="text-3xl font-bold tracking-tight">World Cup 2026 Archive</h2>
            <p className="mx-auto mt-2 max-w-2xl text-muted-foreground">
              All of our World Cup 2026 predictions and analysis are preserved below.
            </p>
          </div>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {archiveLinks.map((link) => (
              <Link key={link.href} href={link.href} className="group">
                <Card className="h-full transition-shadow hover:shadow-md">
                  <CardHeader>
                    <CardTitle className="group-hover:text-sports-green">{link.label}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">{link.description}</p>
                  </CardContent>
                </Card>
              </Link>
            ))}
            <Card className="flex h-full flex-col justify-center border-dashed bg-transparent">
              <CardContent>
                <p className="text-sm text-muted-foreground">
                  Explore the complete archive on the{" "}
                  <Link href="/world-cup/2026" className="font-medium text-sports-green hover:underline">
                    World Cup 2026 archive page
                  </Link>
                  .
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="container mx-auto max-w-7xl px-4 py-16">
        <div className="mb-8 text-center">
          <h2 className="text-3xl font-bold tracking-tight">How It Works</h2>
          <p className="mx-auto mt-2 max-w-2xl text-muted-foreground">
            A transparent, four-step process from data to prediction.
          </p>
        </div>
        <div className="grid gap-6 md:grid-cols-4">
          {steps.map((step, i) => (
            <div key={step.title} className="relative">
              <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-full bg-sports-green/10 font-bold text-sports-green">
                {i + 1}
              </div>
              <step.icon className="mb-2 h-6 w-6 text-sports-blue" />
              <h3 className="font-semibold">{step.title}</h3>
              <p className="mt-1 text-sm text-muted-foreground">{step.description}</p>
            </div>
          ))}
        </div>
        <div className="mt-10 text-center">
          <Link href="/how-we-predict">
            <Button size="lg" variant="secondary">
              Learn How We Predict <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          </Link>
        </div>
      </section>

      {/* FAQ */}
      <section className="border-t bg-muted/30">
        <div className="container mx-auto max-w-3xl px-4 py-16">
          <h2 className="mb-8 text-center text-3xl font-bold tracking-tight">Frequently Asked Questions</h2>
          <FAQSection faqs={homeFAQs} />
        </div>
      </section>
    </>
  )
}
